name: update-flake-lock
on:
  schedule:
    - cron: '3 6 * * 1' # Run weekly on Mondays
permissions:
  contents: write
  pull-requests: write
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install-nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: update-flake-lock
        if: ${{ github.event_name != 'pull_request' }}
        uses: DeterminateSystems/update-flake-lock@28
        with:
          commit-msg: 'build(deps): update flake.lock'
          pr-reviewers: m3l6h
          pr-labels: |
            automated
      - name: print-pr-number
        if: ${{ github.event_name != 'pull_request' }}
        run: "echo PR is #${{ steps.update.outputs.pull-request-number }}"
